### ISSUE TITLE
Extra steps necessary for installation besides pip install?

### ISSUE THREAD

**Issue by cvmartin** [jcheng5/py-shinydashboard#2]
First of all, thanks for bringing `shiny` and `shinydashboard` to python!

I am playing around with the library and I observe that I cannot just run it installing it with the `pip install` instruction defined in`README.md`. 

Specifically, both in my local and in a docker container I get:

```
RuntimeError: Directory '/Users/[MY_PATH]/.venv/lib/python3.9/site-packages/shinydashboard/shinydashboard' does not exist
```
Which I found strange because this is a folder that _is in the repo_. But upon inspection of my `.venv` I can see that indeed it is not there, and if I add the missing files manually, everything runs smooth.

I could put together a little repo-reprex reproducing the error, but this looks like it has more to do with me missing out something about how typescript is translated into JS, for what I see in the `package.json` file ([line 4](https://github.com/jcheng5/py-shinydashboard/blob/bfdb53ccd0d787375a8bbd236b48d08a71b7e56b/srcts/package.json#L4)).

Should I be `build`ing something to make the library work in, say, a docker container?

**Comment by jcheng5** [comment]
Oh yikes, I didn't think anyone would be looking at this yet! You can try `pip install -e ...` for now, but I'll look at fixing that.

**Comment by cvmartin** [comment]
Thanks a lot! Indeed `RUN pip install -e git+https://github.com/jcheng5/py-shinydashboard#egg=shinydashboard` does it.

I think I found the repo hours after it was created by literally googling "py-shinydashboard" by chance. Again, thanks for bringing this to Python, in the last years I've enjoyed a lot using `shiny` and `shinydashboard` for R

**Comment by jcheng5** [comment]
FYI, `-e` should no longer be required, thanks!

**Comment by cvmartin** [comment]
Thanks! :)

**Comment by cvmartin** [comment]
Remarkably, it doesn't work for me yet. If I try to run an app inside a container installing `git+https://github.com/jcheng5/py-shinydashboard` from within `requirements.txt` it still throws an error. 

Not a big deal, I just do `RUN pip install -e git+https://github.com/jcheng5/py-shinydashboard#egg=shinydashboard` afterwards and go on with it. I just thought you would want to know this.
